### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by matthagan15** [strawlab/accelerate-src#8] opened 2022-10-21 22:38 UTC
Hi, not sure if this crate is being maintained but it currently does not work with ndarray with the blas feature on and blas-src with the "accelerate" feature. If these are turned on the user has to manually add a build.rs with "cargo:rustc-link-lib=framework=Accelerate", after which it then seems to work. Not sure why this happens.

**Comment by astraw** [comment] 2022-10-22 21:49
This crate is mature and does not need much maintaining.

I don't think the issue is with `accelerate-src`. Nothing has changed here in a while and things still work for me. I just pushed 96b6e8b46e2fcf1190943e1d9fb9b75f4d0c292a which will run a test every week to ensure this remains the case. Our `build.rs` already has `println!("cargo:rustc-link-lib=framework=Accelerate");` in it. Are you setting your Cargo features to pick up `accelerate-src`? Have you seen https://github.com/blas-lapack-rs/blas-lapack-rs.github.io/wiki? I'm closing this for now but if you have a test which reproduces the issue and shows it is an issue with `accelerate-src`, please re-open this issue. Otherwise, good luck resolving your issue.

**Closed as completed by astraw** 2022-10-22 21:49 UTC
